In [2]:
import numpy as np

In [26]:
def f(x, y):
    return x**2 + y**2

In [70]:
# Parameters:
n = 1
omega = 0.1
alpha_1 = alpha_2 = 1.0
v = np.array([0.0,0.0])
x = (-10) + (10 - (-10)) * np.random.rand(n,2)
x_personal_opt = np.array([10.0,10.0]) # set to worst possible
x_social_opt = np.array([10.0,10.0]) # set to worst possible


for i in range (100):
    r_1 = np.random.rand(1)
    r_2 = np.random.rand(1)
    v = omega * v + r_1 * alpha_1 * (x_personal_opt - x) + r_2 * alpha_2 * (x_social_opt - x)
    x = x + v
    print("x")
    print(x)
    print("personal opt")
    print(x_personal_opt)
    print("social opt")
    print(x_social_opt)
    print("score x")
    print(f(x.item(0), x.item(1)))
    print("score personal opt")
    print(f(x_personal_opt.item(0),x_personal_opt.item(1)))
    if (f(x.item(0), x.item(1)) < f(x_personal_opt.item(0),x_personal_opt.item(1))):
        x_personal_opt = x
    if (f(x.item(0), x.item(1)) < f(x_social_opt.item(0),x_social_opt.item(1))):
        x_social_opt = x

x
[[7.21452021 7.13745568]]
personal opt
[10. 10.]
social opt
[10. 10.]
score x
102.99257554365406
score personal opt
200.0
x
[[8.60578525 8.56721218]]
personal opt
[[7.21452021 7.13745568]]
social opt
[[7.21452021 7.13745568]]
score x
147.45666432761683
score personal opt
102.99257554365406
x
[[6.97807221 6.89446598]]
personal opt
[[7.21452021 7.13745568]]
social opt
[[7.21452021 7.13745568]]
score x
96.22715289882225
score personal opt
102.99257554365406
x
[[6.8153009  6.72719136]]
personal opt
[[6.97807221 6.89446598]]
social opt
[[6.97807221 6.89446598]]
score x
91.70343001176165
score personal opt
96.22715289882225
x
[[6.79902377 6.7104639 ]]
personal opt
[[6.8153009  6.72719136]]
social opt
[[6.8153009  6.72719136]]
score x
91.25705000561379
score personal opt
91.70343001176165
x
[[6.79739606 6.70879115]]
personal opt
[[6.79902377 6.7104639 ]]
social opt
[[6.79902377 6.7104639 ]]
score x
91.21247192782457
score personal opt
91.25705000561379
x
[[6.79723329 6.70862388]]
personal o

91.20751948060476
score personal opt
91.20751948060476
x
[[6.7972152  6.70860529]]
personal opt
[[6.7972152  6.70860529]]
social opt
[[6.7972152  6.70860529]]
score x
91.20751948060476
score personal opt
91.20751948060476
x
[[6.7972152  6.70860529]]
personal opt
[[6.7972152  6.70860529]]
social opt
[[6.7972152  6.70860529]]
score x
91.20751948060476
score personal opt
91.20751948060476
x
[[6.7972152  6.70860529]]
personal opt
[[6.7972152  6.70860529]]
social opt
[[6.7972152  6.70860529]]
score x
91.20751948060476
score personal opt
91.20751948060476
x
[[6.7972152  6.70860529]]
personal opt
[[6.7972152  6.70860529]]
social opt
[[6.7972152  6.70860529]]
score x
91.20751948060476
score personal opt
91.20751948060476
x
[[6.7972152  6.70860529]]
personal opt
[[6.7972152  6.70860529]]
social opt
[[6.7972152  6.70860529]]
score x
91.20751948060476
score personal opt
91.20751948060476
x
[[6.7972152  6.70860529]]
personal opt
[[6.7972152  6.70860529]]
social opt
[[6.7972152  6.70860529]]
score 

array([6.34776868, 7.91731414])